### ISSUE TITLE
Roadmap For Future Releases

### ISSUE THREAD

**Issue by ghivert** [wolfoxco/create-wolfox-stack#1]
- [x] Add textual outputs when repos are being created.
- [ ] Add an animation when repos are being created.
- [ ] Add a congratulations page after creation.
- [ ] Add documentation.
- [ ] Wolfox Scripts.
- [ ] Generic frontend.
